name: ci_meson

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - readme.md

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [ g++-10, g++-12, clang++-12, clang++-14 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup ${{ matrix.compiler }}/
      env:
        CXX: ${{ matrix.compiler }}
    - run: meson test -C ${{ matrix.compiler }}/ -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: ${{ matrix.compiler }}/meson-logs/testlog.txt

  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install meson
    - run: brew install ninja
    - run: meson setup -Dcpp_std=c++11 build/
    - run: meson test -C build/ -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - uses: ilammy/msvc-dev-cmd@v1
    - run: meson setup -Dcpp_std=c++11 c++11
    - run: meson test -C c++11/ -v
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: c++11/meson-logs/testlog.txt
